repositories = [ "habitat-sh/habitat" ]

# Changelog
########################################################################

[[label]]
name = "Changelog: New Feature"
color = "c61d6f"
description = "PRs that add a new feature"
mappings = [ "X-feature" ]

[[label]]
name = "Changelog: Bug Fix"
color = "c61d6f"
description = "PRs that fix an existing bug"
mappings = [ "X-fix" ]

[[label]]
name = "Changelog: Behavioral Change"
color = "c61d6f"
description = "PRs that are classified as a change to existing behavior"
mappings = [ "X-change" ]

# Component
########################################################################

[[label]]
name = "Component: Supervisor"
color = "87b09a"
description = "Related to the Habitat Supervisor (core/hab-sup) component"
mappings = [ "A-supervisor" ]

[[label]]
name = "Component: Launcher"
color = "87b09a"
description = "Related to the Habitat Launcher (core/hab-launcher) component"
mappings = [ "A-launcher" ]

[[label]]
name = "Component: Studio"
color = "87b09a"
description = "Related to the Habitat Studio (core/hab-studio) component"
mappings = [ "A-studio" ]

[[label]]
name = "Component: CLI"
color = "87b09a"
description = "Related to the Habitat CLI (core/hab) component"
mappings = [ "A-cli" ]

# Platform
########################################################################

[[label]]
name = "Platform: Linux"
color = "c3c6c8"
description = "Deals with Linux-specific behavior"
mappings = [ "I-linux" ]

[[label]]
name = "Platform: Windows"
color = "c3c6c8"
description = "Deals with Windows-specific behavior"
mappings = [ "I-windows" ]

[[label]]
name = "Platform: macOS"
color = "c3c6c8"
description = "Deals with macOS-specific behavior"
mappings = [ "I-macOS" ]

# Type
########################################################################

[[label]]
name = "Type: Bug"
color = "ff9012"
description = "Issues that describe broken functionality"
mappings = [ "C-bug" ]

[[label]]
name = "Type: Chore"
color = "ff9012"
description = "Issues for general code and infrastructure maintenance"
mappings = [ "C-chore" ]

[[label]]
name = "Type: Feature"
color = "ff9012"
description = "Issues that describe a new desired feature"
mappings = [ "C-feature" ]

# Source
########################################################################

[[label]]
name = "Source: Internal"
color = "0fb0bf"
description = "Issues raised by Chef employees"

[[label]]
name = "Source: External"
color = "0fb0bf"
description = "Issues raised by non-Chef employees"

########################################################################
# OLD LABELS
########################################################################

[[label]]
name = "A-supervisor"
delete = true

[[label]]
name = "A-studio"
delete = true

[[label]]
name = "A-builder"
delete = true

[[label]]
name = "A-documentation"
color = "87B09A"
mappings = [ "Documentation" ]

[[label]]
name = "A-cli"
delete = true

[[label]]
name = "A-exporter"
color = "87B09A"
mappings = [ "exporters" ]

[[label]]
name = "A-launcher"
delete = true

[[label]]
name = "A-habitat.sh"
color = "87B09A"
mappings = [ "habitat.sh" ]

[[label]]
name = "A-plan-build"
color = "87B09A"
mappings = [ "Plan-Build" ]

[[label]]
name = "A-scaffolding"
color = "87B09A"
mappings = [ "scaffoldings" ]

[[label]]
name = "C-feature"
delete = true

[[label]]
name = "C-bug"
delete = true

[[label]]
name = "C-chore"
delete = true

[[label]]
name = "C-release"
color = "ff9012"
mappings = [ "Release" ]

[[label]]
name = "C-RFC"
color = "ff9012"

[[label]]
name = "E-easy"
color = "4296b4"
mappings = [ "Easy" ]

[[label]]
name = "E-less-easy"
color = "4296b4"

[[label]]
name = "E-hard"
color = "4296b4"

[[label]]
name = "E-mentored"
color = "4296b4"

[[label]]
name = "Epic"
color = "3e4b9e"
mappings = [ "E-helldive", "E-epic" ]

[[label]]
name = "L-rust"
color = "5c6670"

[[label]]
name = "L-html-css"
color = "5c6670"

[[label]]
name = "L-javascript"
color = "5c6670"

[[label]]
name = "L-shell"
color = "5c6670"

[[label]]
name = "S-awaiting-review"
color = "EB6852"
mappings = [ "Ready" ]

[[label]]
name = "S-needs-discussion"
color = "EB6852"
mappings = [ "Discussing" ]

[[label]]
name = "T-Hacktoberfest"
color = "f45942"

[[label]]
name = "T-DO-NOT-MERGE"
color = "d62f3f"
mappings = [ "S-DO-NOT-MERGE" ]

[[label]]
name = "T-stability"
color = "d62f3f"
mappings = [ "STABILITY", "C-STABILITY" ]

[[label]]
name = "T-breaking"
color = "d62f3f"
mappings = [ "C-breaking" ]

[[label]]
name = "T-observability"
color = "d62f3f"

[[label]]
name = "T-help-wanted"
color = "d62f3f"

[[label]]
name = "T-emergent"
color = "d62f3f"

[[label]]
name = "P-1"
color = "3257bc"
mappings = [ "C-critical" ]

[[label]]
name = "P-2"
color = "3257bc"
mappings = [ "C-breaking" ]

[[label]]
name = "P-3"
color = "3257bc"

[[label]]
name = "I-linux"
delete = true

[[label]]
name = "I-macOS"
delete = true

[[label]]
name = "I-windows"
delete = true

[[label]]
name = "V-bldr"
delete = true

[[label]]
name = "V-devx"
color = "0fb0bf"

[[label]]
name = "V-infra"
color = "0fb0bf"

[[label]]
name = "V-sup"
color = "0fb0bf"

[[label]]
name = "V-front-end"
color = "0fb0bf"

[[label]]
name = "V-core-plans"
color = "0fb0bf"

[[label]]
name = "Expeditor: Exclude from Changelog"
color = "0e8a16"

[[label]]
name = "X-feature"
delete = true

[[label]]
name = "X-fix"
delete = true

[[label]]
name = "X-change"
delete = true
