repositories = [
                "chef/chef", "chef/ohai", "chef/cheffish", "chef/chef-zero", "chef/chefstyle", "chef/welcome_bot", "chef/cookstyle", "chef/chef-dk", "chef/jump-in",
                "chef/win32-service", "chef/win32-eventlog", "chef/win32-taskscheduler", "chef/win32-process", "chef/win32-security",
                "chef/win32-file", "chef/win32-dir", "chef/win32-changejournal", "chef/win32-pipe", "chef/win32-sound", "chef/win32-file-security",
                "chef/win32-ipc", "chef/win32-clipboard", "chef/pr-win32ole", "chef/win32-file-stat", "chef/win32-shortcut", "chef/win32-certstore",
                "chef/win32-sapi", "chef/win32-ole", "chef/win32-mmap", "chef/win32-event", "chef/win32-nio", "chef/win32-changenotify", "chef/win32-file-attributes",
                "chef/win32-job", "chef/win32-mutex", "chef/win32-socket", "chef/win32-mailslot", "chef/ffi-win32-extensions", "chef/win32-semaphore",
                "chef/win32-dirmonitor", "chef/mixlib-cli", "chef/mixlib-log", "chef/mixlib-config", "chef/mixlib-authentication",
                "chef/mixlib-shellout", "chef/mixlib-versioning", "chef/mixlib-archive", "chef/knife-ec2", "chef/knife-rackspace", "chef/knife-openstack",
                "chef/knife-azure", "chef/knife-windows", "chef/knife-google", "chef/knife-linode", "chef/knife-push", "chef/knife-opc", "chef/knife-acl",
                "chef/knife-cloud", "chef/knife-reporting", "chef/knife-ec-backup", "chef/knife-kvm", "chef/knife-analytics", "chef/knife-ecs", "chef/knife-vcenter",
                "chef/knife-lpar", "chef/kitchen-appbundle-updater", "chef/kitchen-vcenter", "chef/chef-provisioning", "chef/chef-provisioning-aws",
                "chef/chef-provisioning-fog", "chef/chef-provisioning-ssh", "chef/chef-provisioning-central", "chef/chef-vault", "chef/chef-ruby-lvm",
                "chef/chef-ruby-lvm-attrib", "chef/ffi-libarchive", "chef/chocolatey-packages", "chef/homebrew-chef", "chef/ffi-yajl", "chef/libyajl2-gem",
                "chef/vagrant-omnibus", "chef/appbundler", "chef/rs-chef-api", "chef/omnibus", "chef/appbundle-updater", "chef/opscode-pushy-client",
                "chef/omnibus-software", "chef/chef-workstation", "chef/chef-apply", "chef/chef-manage", "chef/mixlib-install", "chef/mixlib-platform",
                "chef/opscode-pushy-server", "chef/mixlib-platform", "chef/knife-vsphere", "chef/omnitruck", "chef/bento-ya", "chef/artifactory-client",
                "chef/knife-ec-backup", "chef/knife-tidy", "chef/bft", "chef/kitchen-wpar", "chef/oss_project_boilerplate", "chef/dep-selector-libgecode",
                "chef/wmi-lite", "chef/dcob", "chef/community-summits", "chef/folsom_graphite", "chef/stats_hero" ]

### Aspects

[[label]]
color = "d4c5f9"
name = "Aspect: Correctness"

[[label]]
color = "d4c5f9"
name = "Aspect: Integration"

[[label]]
color = "d4c5f9"
name = "Aspect: Packaging"

[[label]]
color = "d4c5f9"
name = "Aspect: Performance"

[[label]]
color = "d4c5f9"
name = "Aspect: Portability"

[[label]]
color = "d4c5f9"
name = "Aspect: Security"

[[label]]
color = "d4c5f9"
name = "Aspect: Stability"

[[label]]
color = "d4c5f9"
name = "Aspect: Testing"

[[label]]
color = "d4c5f9"
name = "Aspect: UX"

[[label]]
color = "d4c5f9"
name = "Aspect: Documentation"
mappings = ["Documentation", "documentation", "Type: Documentation"]

### Expeditor

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip Changelog"
mappings = ["Changelog: Skip Update", "Exclude From Changelog", "Expeditor: Exclude From Changelog"]

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip All"

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip Habitat"

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip Omnibus"
mappings = ["Expeditor: Skip Build"]

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip Version Bump"
mappings = ["Version: Skip Bump"]

[[label]]
color = "bfd4f2"
name = "Expeditor: Bump Version Minor"
mappings = ["Expeditor: Bump Minor Version"]

### Help

[[label]]
color = "d34a00"
name = "Help: Good First Issue"
mappings = ["Easy", "hacktoberfest", "Hacktoberfest", "help wanted", "Help Wanted", "Jump In", "good first issue", "Type: Jump In"]

[[label]]
color = "d34a00"
name = "Help: Help Wanted"


### Platform

[[label]]
color = "a2c429"
name = "Platform: AWS"

[[label]]
color = "a2c429"
name = "Platform: Azure"

[[label]]
color = "a2c429"
name = "Platform: Docker"

[[label]]
color = "a2c429"
name = "Platform: GCP"

[[label]]
color = "a2c429"
name = "Platform: Linux"

[[label]]
color = "a2c429"
name = "Platform: macOS"
mappings = ["Area: Mac"]

[[label]]
color = "a2c429"
name = "Platform: RHEL-like"
mappings = ["Area: Enterprise Linux"]

[[label]]
color = "a2c429"
name = "Platform: Debian-like"
mappings = ["Area: Ubuntu"]

[[label]]
color = "a2c429"
name = "Platform: VMware"

[[label]]
color = "a2c429"
name = "Platform: Unix-like"
mappings = ["Area: SmartOS", "Area: Solaris", "Area: BSD", "Area: AIX"]

[[label]]
color = "a2c429"
name = "Platform: Windows"
mappings = ["Area: Windows"]

### Status

[[label]]
color = "0052cc"
name = "Status: Adopted"

[[label]]
color = "0052cc"
name = "Status: Needs Adoption"
mappings = ["Finish for Merge", "Status: Finish for Merge"]

color = "0052cc"
name = "Status: Incomplete"
mappings = ["Incomplete Contribution", "in progress", "Do Not Merge"]

### Triage

[[label]]
color = "f49866"
name = "Triage: Support"

[[label]]
color = "f49866"
name = "Triage: Not Reproducible"

[[label]]
color = "f49866"
name = "Triage: Confirmed"
mappings = ["Triaged", "Status: Confirmed"]

[[label]]
color = "f49866"
name = "Triage: Needs Information"
mappings = ["Status: Pending Contributor Response", "Waiting for Contributor Response", "Waiting", "Feedback Requested", "waitingresponse", "Waiting on Contributor", "Waiting on Feedback"]

[[label]]
color = "f49866"
name = "Triage: Declined"
mappings = ["wontfix", "Status: Won't Fix"]

[[label]]
color = "f49866"
name = "Triage: Duplicate"
mappings = [ "duplicate", "Duplicate", "Status: Duplicate" ]

### Type

[[label]]
color = "bfe5bf"
name = "Type: Chore"

[[label]]
color = "bfe5bf"
name = "Type: Breaking Change"

[[label]]
color = "bfe5bf"
name = "Type: Deprecation"

[[label]]
color = "bfe5bf"
name = "Type: Question"

[[label]]
color = "bfe5bf"
name = "Type: Tech Debt"

[[label]]
color = "bfe5bf"
name = "Type: Regression"
mappings = ["Regression"]

[[label]]
color = "bfe5bf"
mappings = [ "Bug", "bug", "Bug Fix" ]
name = "Type: Bug"

[[label]]
color = "bfe5bf"
name = "Type: Enhancement"
mappings = ["Enhancement", "enhancement", "Improvement", "New Feature", "Feature"]

[[label]]
color = "bfe5bf"
name = "Type: Feature Request"
mappings = ["Feature Request"]

color = "bfe5bf"
name = "Type: Regression"
mappings = ["Regression"]

### Priority

[[label]]
color = "eb6420"
name = "Priority: Critical"
mappings = ["High Priority"]

[[label]]
color = "eb6420"
name = "Priority: Medium"
mappings = ["Medium Priority"]

[[label]]
color = "eb6420"
name = "Priority: Low"
mappings = ["Low Priority"]

### Old labels to delete

[[label]]
delete = true
name = "CLA Verified"

[[label]]
delete = true
name = "Signed CLA"

[[label]]
delete = true
name = "CLA Needed"

[[label]]
delete = true
name = "General"

[[label]]
delete = true
name = "office hours"

[[label]]
delete = true
name = "Help"

[[label]]
delete = true
name = "Delivery Change Created"

[[label]]
delete = true
name = "Status: Ready for Merge"

[[label]]
delete = true
name = "Status: Pending Maintainer Review"

[[label]]
delete = true
name = "Signed CLA"

[[label]]
name = "invalid"
delete = true

[[label]]
name = "question"
delete = true

[[label]]
name = "Attack List"
delete = true

[[label]]
name = "Tech Cleanup"
delete = true

[[label]]
name = "Discussion"
delete = true

[[label]]
name = "question"
delete = true

[[label]]
name = "Needs Action"
delete = true

[[label]]
name = "Waiting on Feedback"
delete = true

[[label]]
name = "good first issue"
delete = true

[[label]]
name = "Reviewed"
delete = true
