[organizations]
type = "public"
orgs = ["chef"]
blacklist = ["chef/chef-web-docs",
             "chef/chef-community-slack-meetings",
             "chef/chef-rfc",
             "chef/community-summits",
             "chef/devops-kungfu",
             "chef/dmidecode_collection",
             "chef/os_release"]

### Aspects

[[label]]
color = "d4c5f9"
name = "Aspect: Correctness"

[[label]]
color = "d4c5f9"
name = "Aspect: Integration"

[[label]]
color = "d4c5f9"
name = "Aspect: Scalability"
mappings = ["scalability"]

[[label]]
color = "d4c5f9"
name = "Aspect: Packaging"
mappings = ["Area: Packaging"]

[[label]]
color = "d4c5f9"
name = "Aspect: Performance"
mappings = ["Type: Performance"]

[[label]]
color = "d4c5f9"
name = "Aspect: Portability"

[[label]]
color = "d4c5f9"
name = "Aspect: Security"
mappings = ["Security"]

[[label]]
color = "d4c5f9"
name = "Aspect: Stability"

[[label]]
color = "d4c5f9"
name = "Aspect: Testing"

[[label]]
color = "d4c5f9"
name = "Aspect: UX"
mappings = ["Type: Delight Blocker"]

[[label]]
color = "d4c5f9"
name = "Aspect: UI"

[[label]]
color = "d4c5f9"
name = "Aspect: Documentation"
mappings = ["Documentation", "documentation", "Type: Documentation"]

### Size

[[label]]
name = "Size: XS"
mappings = ["XS"]
color = "008672"

[[label]]
name = "Size: S"
mappings = ["S", "Small"]
color = "008672"

[[label]]
name = "Size: M"
mappings = ["M", "Medium"]
color = "008672"

[[label]]
name = "Size: L"
mappings = ["L", "Large"]
color = "008672"

[[label]]
name = "Size: XL"
mappings = ["XL"]
color = "008672"

[[label]]
name = "Size: XXL"
mappings = ["XXL"]
color = "008672"

### Expeditor

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip Changelog"
mappings = ["Changelog: Skip Update", "Exclude From Changelog", "Expeditor: Exclude From Changelog", "No_Changelog"]

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip All"

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip Habitat"

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip Omnibus"
mappings = ["Expeditor: Skip Build", "Omnibus: Skip Build"]

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip Version Bump"
mappings = ["Version: Skip Bump"]

[[label]]
color = "bfd4f2"
name = "Expeditor: Bump Version Minor"
mappings = ["Expeditor: Bump Minor Version"]

### Help

[[label]]
color = "d34a00"
name = "Help: Good First Issue"
mappings = ["Easy", "hacktoberfest", "Hacktoberfest", "help wanted", "Help Wanted", "Jump In", "good first issue", "Type: Jump In"]

[[label]]
color = "d34a00"
name = "Help: Help Wanted"

### Platform

[[label]]
color = "a2c429"
name = "Platform: AWS"

[[label]]
color = "a2c429"
name = "Platform: Azure"

[[label]]
color = "a2c429"
name = "Platform: Docker"

[[label]]
color = "a2c429"
name = "Platform: GCP"

[[label]]
color = "a2c429"
name = "Platform: Linux"

[[label]]
color = "a2c429"
name = "Platform: macOS"
mappings = ["Area: Mac"]

[[label]]
color = "a2c429"
name = "Platform: RHEL-like"
mappings = ["Area: Enterprise Linux"]

[[label]]
color = "a2c429"
name = "Platform: Debian-like"
mappings = ["Area: Ubuntu"]

[[label]]
color = "a2c429"
name = "Platform: VMware"

[[label]]
color = "a2c429"
name = "Platform: Unix-like"
mappings = ["Area: SmartOS", "Area: Solaris", "Area: BSD", "Area: AIX"]

[[label]]
color = "a2c429"
name = "Platform: Windows"
mappings = ["Area: Windows"]

### Status

[[label]]
color = "0052cc"
name = "Status: Adopted"

[[label]]
color = "0052cc"
name = "Status: Needs Adoption"
mappings = ["Finish for Merge", "Status: Finish for Merge", "Status: Abandoned"]

[[label]]
color = "0052cc"
name = "Status: Incomplete"
mappings = ["Incomplete Contribution", "in progress", "Do Not Merge", "do-not-merge", "In Progress", "Status: In Progress", "Status: Blocked", "Status: On Hold"]

[[label]]
color = "0052cc"
name = "Status: Waiting on Contributor"

### Triage

[[label]]
color = "f49866"
name = "Triage: Support"

[[label]]
color = "f49866"
name = "Triage: Not Reproducible"

[[label]]
color = "f49866"
name = "Triage: Confirmed"
mappings = ["Triaged", "Status: Confirmed"]

[[label]]
color = "f49866"
name = "Triage: Needs Information"
mappings = ["Status: Pending Contributor Response", "Waiting for Contributor Response", "Waiting", "Feedback Requested", "waitingresponse", "Waiting on Contributor", "Waiting on Feedback"]

[[label]]
color = "f49866"
name = "Triage: Declined"
mappings = ["wontfix", "Status: Won't Fix", "Won't Fix"]

[[label]]
color = "f49866"
name = "Triage: Duplicate"
mappings = [ "duplicate", "Duplicate", "Status: Duplicate" ]

### Type

[[label]]
color = "bfe5bf"
name = "Type: Chore"
mappings = ["Type: Maintenance"]

[[label]]
color = "bfe5bf"
name = "Type: Breaking Change"

[[label]]
color = "bfe5bf"
name = "Type: Deprecation"

[[label]]
color = "bfe5bf"
name = "Type: Question"
mappings = ["question"]

[[label]]
color = "bfe5bf"
name = "Type: Tech Debt"
mappings = ["Tech Cleanup", "Debt"]

[[label]]
color = "bfe5bf"
name = "Type: Regression"
mappings = ["Regression"]

[[label]]
color = "bfe5bf"
mappings = [ "Bug", "bug", "Bug Fix" ]
name = "Type: Bug"

[[label]]
color = "bfe5bf"
name = "Type: Enhancement"
mappings = ["Enhancement", "enhancement", "Improvement", "Type: Feature Request" ]

[[label]]
color = "bfe5bf"
name = "Type: Feature Request"
mappings = ["Feature Request", "New Feature", "Feature"]

color = "bfe5bf"
name = "Type: Regression"
mappings = ["Regression"]

### Priority

[[label]]
color = "eb6420"
name = "Priority: Critical"
mappings = ["High Priority", "critical", "Priority: High"]

[[label]]
color = "eb6420"
name = "Priority: Medium"
mappings = ["Medium Priority"]

[[label]]
color = "eb6420"
name = "Priority: Low"
mappings = ["Low Priority"]

### Old labels to delete

[[label]]
delete = true
name = "CLA Verified"

[[label]]
delete = true
name = "CLA Needed"

[[label]]
delete = true
name = "General"

[[label]]
delete = true
name = "office hours"

[[label]]
delete = true
name = "Help"

[[label]]
delete = true
name = "Delivery Change Created"

[[label]]
delete = true
name = "Status: Ready for Merge"

[[label]]
delete = true
name = "Status: Pending Maintainer Review"

[[label]]
delete = true
name = "Signed CLA"

[[label]]
name = "invalid"
delete = true

[[label]]
name = "Attack List"
delete = true

[[label]]
name = "Discussion"
delete = true

[[label]]
name = "Needs Action"
delete = true

[[label]]
name = "Type: Retest for Status"
delete = true

[[label]]
name = "Reviewed"
delete = true

[[label]]
name = "Review Required"
delete = true

[[label]]
name = "Status: Maintainer Review Needed"
delete = true

[[label]]
name = "investigate"
delete = true
