repositories = [
              "chef/anka-buildkite-plugin",
              "chef/appbundle-updater",
              "chef/appbundler",
              "chef/artifactory-client",
              "chef/automate-liveness-agent",
              "chef/bento-ya",
              "chef/bento",
              "chef/bft",
              "chef/bundle-merge",
              "chef/chef_authn",
              "chef/chef_backup",
              "chef/chef_certgen",
              "chef/chef_req",
              "chef/chef_secrets",
              "chef/chef-apply",
              "chef/chef-dk",
              "chef/chef-load",
              "chef/chef-manage",
              "chef/chef-powershell-shim",
              "chef/chef-provisioning-aws",
              "chef/chef-provisioning-fog",
              "chef/chef-provisioning-ssh",
              "chef/chef-provisioning",
              "chef/chef-push",
              "chef/chef-ruby-lvm-attrib",
              "chef/chef-ruby-lvm",
              "chef/chef-telemetry",
              "chef/chef-triage-app",
              "chef/chef-vault-testfixtures",
              "chef/chef-vault",
              "chef/chef-web-core",
              "chef/chef-workstation",
              "chef/chef-zero",
              "chef/chef",
              "chef/cheffish",
              "chef/chefops-plans",
              "chef/chefstyle",
              "chef/chocolatey-packages",
              "chef/ci-studio-common",
              "chef/community_cookbook_releaser",
              "chef/community_engineering_cookbooks",
              "chef/community-summits",
              "chef/concrete",
              "chef/cookbook-omnifetch",
              "chef/cookstyle",
              "chef/dcob",
              "chef/delivery-cli",
              "chef/dep-selector-libgecode",
              "chef/devchef",
              "chef/efast_xs",
              "chef/erlang-crypto2",
              "chef/fast-log-erlang",
              "chef/fastmsi-custom-action",
              "chef/ffi-libarchive",
              "chef/ffi-win32-extensions",
              "chef/ffi-yajl",
              "chef/fixie",
              "chef/folsom_graphite",
              "chef/habitat-exporters",
              "chef/homebrew-chef",
              "chef/homebrew-chefops-tools",
              "chef/homebrew-okta_aws",
              "chef/inspec-chef-server",
              "chef/inspec-oneview",
              "chef/jump-in",
              "chef/kitchen-appbundle-updater",
              "chef/kitchen-vcenter",
              "chef/kitchen-wpar",
              "chef/knife-acl",
              "chef/knife-azure",
              "chef/knife-cloud",
              "chef/knife-ec-backup",
              "chef/knife-ec2",
              "chef/knife-google",
              "chef/knife-kvm",
              "chef/knife-linode",
              "chef/knife-lpar",
              "chef/knife-opc",
              "chef/knife-openstack",
              "chef/knife-push",
              "chef/knife-rackspace",
              "chef/knife-reporting",
              "chef/knife-tidy",
              "chef/knife-vcenter",
              "chef/knife-vsphere",
              "chef/knife-windows",
              "chef/lambda_ebs_snapshot",
              "chef/libarchive-rust",
              "chef/libarchive3-sys",
              "chef/libyajl2-gem",
              "chef/license_scout",
              "chef/marketo_chef",
              "chef/mini_s3",
              "chef/mixer",
              "chef/mixlib-archive",
              "chef/mixlib-authentication",
              "chef/mixlib-cli",
              "chef/mixlib-config",
              "chef/mixlib-install",
              "chef/mixlib-log",
              "chef/mixlib-platform",
              "chef/mixlib-shellout",
              "chef/mixlib-versioning",
              "chef/moser",
              "chef/ng2-feature-flags",
              "chef/ohai",
              "chef/omniauth-chef-oauth2",
              "chef/omniauth-chef",
              "chef/omnibus-ctl",
              "chef/omnibus-software",
              "chef/omnibus-toolchain",
              "chef/omnibus",
              "chef/omnitruck",
              "chef/opscode-pushy-client",
              "chef/opscode-pushy-server",
              "chef/opscode-pushy-simulator",
              "chef/opscode-rebar-templates",
              "chef/opscoderl_folsom",
              "chef/opscoderl_httpc",
              "chef/opscoderl_wm",
              "chef/oss_project_boilerplate",
              "chef/pr-win32ole",
              "chef/pr-win32ole",
              "chef/proxy_tests",
              "chef/push_jobs_test_infra",
              "chef/qa-chef-server-cluster",
              "chef/rs-chef-api",
              "chef/scaffolding-go",
              "chef/sqerl",
              "chef/stats_hero",
              "chef/supermarket",
              "chef/tf_delivery_cluster",
              "chef/travis-sugar",
              "chef/vagrant-omnibus",
              "chef/vault-dynamodb",
              "chef/welcome_bot",
              "chef/win32-certstore",
              "chef/win32-changejournal",
              "chef/win32-changenotify",
              "chef/win32-clipboard",
              "chef/win32-dir",
              "chef/win32-dirmonitor",
              "chef/win32-event",
              "chef/win32-eventlog",
              "chef/win32-file-attributes",
              "chef/win32-file-security",
              "chef/win32-file-stat",
              "chef/win32-file",
              "chef/win32-ipc",
              "chef/win32-job",
              "chef/win32-mailslot",
              "chef/win32-mmap",
              "chef/win32-mutex",
              "chef/win32-nio",
              "chef/win32-ole",
              "chef/win32-pipe",
              "chef/win32-process",
              "chef/win32-sapi",
              "chef/win32-security",
              "chef/win32-semaphore",
              "chef/win32-service",
              "chef/win32-shortcut",
              "chef/win32-socket",
              "chef/win32-sound",
              "chef/win32-taskscheduler",
              "chef/windows-cng",
              "chef/windows-openssl-build",
              "chef/wmi-lite",
              "chef/wordpress-tribe-events-api-plugin",
              "chef/zeromq4-x"
                ]

### Aspects

[[label]]
color = "d4c5f9"
name = "Aspect: Correctness"

[[label]]
color = "d4c5f9"
name = "Aspect: Integration"

[[label]]
color = "d4c5f9"
name = "Aspect: Packaging"
mappings = ["Area: Packaging"]

[[label]]
color = "d4c5f9"
name = "Aspect: Performance"
mappings = ["Type: Performance"]

[[label]]
color = "d4c5f9"
name = "Aspect: Portability"

[[label]]
color = "d4c5f9"
name = "Aspect: Security"
mappings = ["Security"]

[[label]]
color = "d4c5f9"
name = "Aspect: Stability"

[[label]]
color = "d4c5f9"
name = "Aspect: Testing"

[[label]]
color = "d4c5f9"
name = "Aspect: UX"
mappings = ["Type: Delight Blocker"]

[[label]]
color = "d4c5f9"
name = "Aspect: UI"

[[label]]
color = "d4c5f9"
name = "Aspect: Documentation"
mappings = ["Documentation", "documentation", "Type: Documentation"]

### Expeditor

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip Changelog"
mappings = ["Changelog: Skip Update", "Exclude From Changelog", "Expeditor: Exclude From Changelog", "No_Changelog"]

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip All"

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip Habitat"

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip Omnibus"
mappings = ["Expeditor: Skip Build"]

[[label]]
color = "bfd4f2"
name = "Expeditor: Skip Version Bump"
mappings = ["Version: Skip Bump"]

[[label]]
color = "bfd4f2"
name = "Expeditor: Bump Version Minor"
mappings = ["Expeditor: Bump Minor Version"]

### Help

[[label]]
color = "d34a00"
name = "Help: Good First Issue"
mappings = ["Easy", "hacktoberfest", "Hacktoberfest", "help wanted", "Help Wanted", "Jump In", "good first issue", "Type: Jump In"]

[[label]]
color = "d34a00"
name = "Help: Help Wanted"

### Platform

[[label]]
color = "a2c429"
name = "Platform: AWS"

[[label]]
color = "a2c429"
name = "Platform: Azure"

[[label]]
color = "a2c429"
name = "Platform: Docker"

[[label]]
color = "a2c429"
name = "Platform: GCP"

[[label]]
color = "a2c429"
name = "Platform: Linux"

[[label]]
color = "a2c429"
name = "Platform: macOS"
mappings = ["Area: Mac"]

[[label]]
color = "a2c429"
name = "Platform: RHEL-like"
mappings = ["Area: Enterprise Linux"]

[[label]]
color = "a2c429"
name = "Platform: Debian-like"
mappings = ["Area: Ubuntu"]

[[label]]
color = "a2c429"
name = "Platform: VMware"

[[label]]
color = "a2c429"
name = "Platform: Unix-like"
mappings = ["Area: SmartOS", "Area: Solaris", "Area: BSD", "Area: AIX"]

[[label]]
color = "a2c429"
name = "Platform: Windows"
mappings = ["Area: Windows"]

### Status

[[label]]
color = "0052cc"
name = "Status: Adopted"

[[label]]
color = "0052cc"
name = "Status: Needs Adoption"
mappings = ["Finish for Merge", "Status: Finish for Merge"]

color = "0052cc"
name = "Status: Incomplete"
mappings = ["Incomplete Contribution", "in progress", "Do Not Merge", "do-not-merge", "In Progress"]

color = "0052cc"
name = "Status: Waiting on Contributor"

### Triage

[[label]]
color = "f49866"
name = "Triage: Support"

[[label]]
color = "f49866"
name = "Triage: Not Reproducible"

[[label]]
color = "f49866"
name = "Triage: Confirmed"
mappings = ["Triaged", "Status: Confirmed"]

[[label]]
color = "f49866"
name = "Triage: Needs Information"
mappings = ["Status: Pending Contributor Response", "Waiting for Contributor Response", "Waiting", "Feedback Requested", "waitingresponse", "Waiting on Contributor", "Waiting on Feedback"]

[[label]]
color = "f49866"
name = "Triage: Declined"
mappings = ["wontfix", "Status: Won't Fix", "Won't Fix"]

[[label]]
color = "f49866"
name = "Triage: Duplicate"
mappings = [ "duplicate", "Duplicate", "Status: Duplicate" ]

### Type

[[label]]
color = "bfe5bf"
name = "Type: Chore"

[[label]]
color = "bfe5bf"
name = "Type: Breaking Change"

[[label]]
color = "bfe5bf"
name = "Type: Deprecation"

[[label]]
color = "bfe5bf"
name = "Type: Question"
mappings = ["question"]

[[label]]
color = "bfe5bf"
name = "Type: Tech Debt"
mappings = ["Tech Cleanup", "Debt"]

[[label]]
color = "bfe5bf"
name = "Type: Regression"
mappings = ["Regression"]

[[label]]
color = "bfe5bf"
mappings = [ "Bug", "bug", "Bug Fix" ]
name = "Type: Bug"

[[label]]
color = "bfe5bf"
name = "Type: Enhancement"
mappings = ["Enhancement", "enhancement", "Improvement"]

[[label]]
color = "bfe5bf"
name = "Type: Feature Request"
mappings = ["Feature Request", "New Feature", "Feature"]

color = "bfe5bf"
name = "Type: Regression"
mappings = ["Regression"]

### Priority

[[label]]
color = "eb6420"
name = "Priority: Critical"
mappings = ["High Priority"]

[[label]]
color = "eb6420"
name = "Priority: Medium"
mappings = ["Medium Priority"]

[[label]]
color = "eb6420"
name = "Priority: Low"
mappings = ["Low Priority"]

### Old labels to delete

[[label]]
delete = true
name = "CLA Verified"

[[label]]
delete = true
name = "CLA Needed"

[[label]]
delete = true
name = "General"

[[label]]
delete = true
name = "office hours"

[[label]]
delete = true
name = "Help"

[[label]]
delete = true
name = "Delivery Change Created"

[[label]]
delete = true
name = "Status: Ready for Merge"

[[label]]
delete = true
name = "Status: Pending Maintainer Review"

[[label]]
delete = true
name = "Signed CLA"

[[label]]
name = "invalid"
delete = true

[[label]]
name = "question"
delete = true

[[label]]
name = "Attack List"
delete = true

[[label]]
name = "Discussion"
delete = true

[[label]]
name = "question"
delete = true

[[label]]
name = "Needs Action"
delete = true

[[label]]
name = "Area: AIX"
delete = true

[[label]]
name = "Area: BSD"
delete = true

[[label]]
name = "Area: Ubuntu"
delete = true

[[label]]
name = "Area: Solaris"
delete = true

[[label]]
name = "Area: Solaris"
delete = true

[[label]]
name = "Area: Mac"
delete = true

[[label]]
name = "Area: Windows"
delete = true

[[label]]
name = "Area: Enterprise Linux"
delete = true

[[label]]
name = "Waiting on Feedback"
delete = true

[[label]]
name = "Type: Performance"
delete = true

[[label]]
name = "Type: Retest for Status "
delete = true

[[label]]
name = "Area: Packaging"
delete = true

[[label]]
name = "Type: Delight Blocker"
delete = true

[[label]]
name = "good first issue"
delete = true

[[label]]
name = "Reviewed"
delete = true

[[label]]
name = "Security"
delete = true

[[label]]
name = "Version: Skip Bump"
delete = true

[[label]]
name = "wontfix"
delete = true

[[label]]
name = "question"
delete = true

[[label]]
name = "enhancement"
delete = true

[[label]]
name = "duplicate"
delete = true

[[label]]
name = "Review Required"
delete = true

[[label]]
name = "bug"
delete = true

[[label]]
name = "New Feature"
delete = true

[[label]]
name = "No_Changelog"
delete = true

[[label]]
name = "investigate"
delete = true
