repositories = ["chef/paprika"]

[[label]]
color = "CCCCCC"
name = "0 - Backlog"

[[label]]
color = "CCCCCC"
name = "1 - Ready"

[[label]]
color = "CCCCCC"
name = "2 - Working"

[[label]]
color = "CCCCCC"
name = "3 - Done"

[[label]]
color = "ededed"
name = "All Commit Authors are CLA Signers"

[[label]]
color = "bfe5bf"
name = "All Committers are CLA Signers"

[[label]]
color = "fc2929"
name = "bug"

[[label]]
color = "ededed"
name = "cool"

[[label]]
color = "ededed"
name = "coolness"

[[label]]
color = "cccccc"
name = "duplicate"

[[label]]
color = "84b6eb"
name = "enhancement"

[[label]]
color = "e6e6e6"
name = "invalid"

[[label]]
color = "ededed"
name = "LGPA"

[[label]]
color = "ededed"
name = "Long-running"

[[label]]
color = "ededed"
name = "ohai"

[[label]]
color = "cc317c"
name = "question"

[[label]]
color = "8ED41E"
name = "Signed CLA"

[[label]]
color = "ffffff"
name = "wontfix"
